## Packages
- Ready to use Python scripts
- Thousands of packages
- PyPI - the Python Package Index
    - The Python Package Index is a repository of software for the Python programming language. There are currently 121,055 packages here.
    - https://pypi.python.org/pypi
- pip is already installed 
    - pip3 install SomePackage - package installation system for Python         
    #run the code on command or terminal
    - Numpy
    - Matplotlib
    

In [1]:
import numpy as np # Be consistent

### Why we need NumPy?
Lets remember the list
- Hold different data types (number, string)
- Change, add, remove, replace
- Fast but not enough
- Need more for Data Science

In [2]:
#Lets create two lists

In [4]:
weight_kg = [75,80,85,100,55,67, 120]
height_m = [1.91,1.45, 1.67, 1.59, 1.80,1.90, 1.69]

In [ ]:
# BMI = weight_kg / height**2

## NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numeric Python
- Alternative to Python List: NumPy Array
- Calculations over entire arrays
- Easy and Fast

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

#### From a Python List
We can create an array by directly converting a list or list of lists:

In [5]:
print(weight_kg)
print(height_m)

[75, 80, 85, 100, 55, 67, 120]
[1.91, 1.45, 1.67, 1.59, 1.8, 1.9, 1.69]


In [6]:
weight = np.array(weight_kg)

In [7]:
height =np.array(height_m)

In [8]:
BMI = weight / height**2

In [9]:
print(BMI)

[ 20.55864697  38.04994055  30.47796622  39.55539733  16.97530864
  18.55955679  42.0153356 ]


In [10]:
my_list = [1,2,3]

In [11]:
my_list + my_list   # Concatenate

[1, 2, 3, 1, 2, 3]

In [12]:
my_array1 = np.array([1,2,3])

In [13]:
my_array2 = np.array([4,5,6])

In [14]:
print(my_array1 + my_array2)
print(my_array1 - my_array2)
print(my_array1 * my_array2)
print(my_array1 / my_array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [15]:
print(my_array1 +10) # Broadcasting
print(my_array1 *10)

[11 12 13]
[10 20 30]


## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

### Array creation
#### List of values

np.array([1,2,3,4])

In [19]:
a = np.array([0,1,2,3,4,5,6,7,8])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
dtype = np.float16

In [21]:
np.array(a, float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### arange

Return evenly spaced values within a given interval.
- np.arange([start,] stop[, step,], dtype=None)

In [23]:
# Lets try

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Lets try

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [26]:
# Lets try (2,10,2)

array([2, 4, 6, 8])

In [27]:
np.arange(2,10,2, dtype = float)

array([ 2.,  4.,  6.,  8.])

### linspace
- Return evenly spaced numbers over a specified interval.

- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

- Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].

- The endpoint of the interval can optionally be excluded.

In [ ]:
# Lets try

In [22]:
np.linspace(1,10)

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [29]:
np.linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [30]:
np.linspace(0,10, 11, endpoint = False)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909])

In [31]:
np.linspace(0,10,5,retstep = True)

(array([  0. ,   2.5,   5. ,   7.5,  10. ]), 2.5)

### zeros and ones

- Generate arrays of zeros or ones
- zeros(shape, dtype=float)

In [23]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
np.zeros((5,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
np.zeros((5,3), dtype = np.float32)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [26]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [27]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

## eye

Creates an identity matrix

In [28]:
np.eye(5) # N=M

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [31]:
# Lets try N = 3, M=5 
np.eye(3,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.]])

In [32]:
np.eye(5,6,1)

array([[ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [29]:
np.eye(5,5,-2)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [30]:
np.random? # check this out

In [42]:
# Create 2 rand numbers between 0,1

array([ 0.01463796,  0.44875306])

In [43]:
np.random.rand(3,5)

array([[ 0.23629542,  0.78558231,  0.58072101,  0.766977  ,  0.28893693],
       [ 0.14418471,  0.72594799,  0.67920762,  0.70707471,  0.99910734],
       [ 0.10480316,  0.41047337,  0.79213335,  0.81241647,  0.23012222]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [44]:
np.random.randn(2)

array([-1.03700311, -1.58909694])

In [45]:
np.random.randn(3,5)

array([[ 0.71822648,  0.46849623, -0.10506841,  0.72631335,  0.40231448],
       [ 0.70913913,  0.70364453, -0.57089285,  1.70369297, -0.49850369],
       [-0.21437417,  0.58920875,  1.94879918, -0.89897057,  0.95654561]])

### randint
- Return random integers from `low` (inclusive) to `high` (exclusive).
- Similar to randbetween in excel
- randint(low, high=None, size=None, dtype='l')

In [33]:
# Lets create a random integer less than 10
np.random.randint(10)

4

In [34]:
# Lets create a random integer between 5 and 100
np.random.randint(5,100,10)

array([31, 48, 54, 74, 78,  5, 87, 41, 62, 48])

In [48]:
# Lets create 10 random integers between 1 and 100

array([94, 61, 98, 49, 20, 55, 84, 32, 96, 38])

In [50]:
np.random.randint(100, size =6)

array([53, 86, 54, 13, 80, 89])

In [35]:
# Lets create size = (3,5) random integer numbers matrix
arr = np.random.randint(100, size =(3,5))
print(arr)

[[63 85 25 65 18]
 [73 57  9 40  2]
 [71  1 99 64 25]]


In [31]:
np.random.binomial(5,0.5,10 ) # Result of flipping a coin 5 times 10 trials

array([2, 2, 2, 4, 2, 3, 4, 3, 2, 4])

In [53]:
np.random.random((5,3,2))

array([[[ 0.45649005,  0.33965666],
        [ 0.34810051,  0.63216221],
        [ 0.39733102,  0.29281573]],

       [[ 0.16676756,  0.6308421 ],
        [ 0.78202677,  0.80460039],
        [ 0.59510734,  0.42400139]],

       [[ 0.72799681,  0.14185725],
        [ 0.57528792,  0.76939608],
        [ 0.84255012,  0.2219795 ]],

       [[ 0.02284527,  0.44511125],
        [ 0.70190981,  0.48172829],
        [ 0.15651147,  0.48681069]],

       [[ 0.26480255,  0.6605629 ],
        [ 0.58939515,  0.27552206],
        [ 0.24159327,  0.99983106]]])

In [36]:
#WHAT IS SEED AGAIN??
np.random.seed(123)

In [37]:
np.random.randint(0,100,3)

array([66, 92, 98])

In [38]:
np.random.randint(0,100,3)

array([17, 83, 57])

In [39]:
np.random.seed(123)

In [40]:
np.random.randint(0,100,6)

array([66, 92, 98, 17, 83, 57])

## Shape

Shape is an attribute that arrays have:

In [59]:
# Vector
print(BMI)
# Lets get the shape of BMI vector

[ 20.55864697  38.04994055  30.47796622  39.55539733  16.97530864
  18.55955679  42.0153356 ]


(7,)

In [37]:
print(a)
a.shape

[0 1 2 3 4 5 6 7 8]


(9,)

2D Numpy

In [41]:
my_matrix = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]
my_matrix

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [42]:
# Lets use the list of lists to create the Numpy array called np_matrix
np_matrix = np.array(my_matrix)
print(np_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
# Lets see the shape
np_matrix.shape

(3, 5)

Multi array

In [64]:
my_multi = np.random.randint(0,100,(2,3,4))
print(my_multi)

[[[86 97 96 47]
  [73 32 46 96]
  [25 83 78 36]]

 [[96 80 68 49]
  [55 67  2 84]
  [39 66 84 47]]]


## Reshape
Returns an array containing the same data with a new shape.

In [47]:
arr = np.arange(0,15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [48]:
# Lets reshape (3,5)
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
# Notice the two sets of brackets
arr.reshape(1,15) # Row matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [50]:
arr.reshape(1,15).shape

(1, 15)

In [52]:
# Lets create a Column matrix using arr
arr.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [53]:
arr.reshape(15,1).shape

(15, 1)

### NumPy Indexing- Subsetting
If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the ithith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:


In [71]:
print(BMI)

[ 20.55864697  38.04994055  30.47796622  39.55539733  16.97530864
  18.55955679  42.0153356 ]


In [72]:
BMI[0]

20.558646966914285

In [73]:
print(BMI[1])
print(BMI[2])

38.049940547
30.4779662232


In [74]:
print(BMI[1:3])
print(BMI[:2])

[ 38.04994055  30.47796622]
[ 20.55864697  38.04994055]


To index from the end of the array, you can use negative indices:

In [75]:
BMI[-2]

18.559556786703602

In [76]:
BMI[-1]

42.015335597493092

### Subsetting 2D

In [55]:
# Lets create (3,5) matrix for numbers 0- 15
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [57]:
# First row
arr[0]

array([0, 1, 2, 3, 4])

In [79]:
arr[1]

array([5, 6, 7, 8, 9])

In [58]:
# Lets get the first number
arr[0,0]

0

In [64]:
# Lets get the last number
#arr[2,4]
arr[-1,-1]

14

In [65]:
arr[1][2]

7

In [83]:
arr[1,2]

7

In [84]:
arr[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
arr[0,:]

array([0, 1, 2, 3, 4])

In [86]:
arr[:,0]

array([ 0,  5, 10])

In [68]:
# Lets get the first two rows (0-9)
arr[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
# Lets get the numbers in the last row from 11 to 14 
arr[2,1:]

array([11, 12, 13, 14])

In [72]:
# Lets get 10
arr[2,0]

10

In [76]:
# Lets get the "red" numbers: 2 3 7 8 
arr[0:2,2:4]

array([[2, 3],
       [7, 8]])

In [79]:
# Lets get the "red" numbers in figure top
#arr[:,[0,1,4]]
arr[:,::2] 
#double colons skip the column in the middle

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [80]:
# Lets get the "red" numbers in figure bottom 0 3 10 13
arr[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [84]:
app = np.zeros((5,5))
app[1:4,1:4] = 100
print(app)

[[   0.    0.    0.    0.    0.]
 [   0.  100.  100.  100.    0.]
 [   0.  100.  100.  100.    0.]
 [   0.  100.  100.  100.    0.]
 [   0.    0.    0.    0.    0.]]


# Computation on NumPy Arrays: Universal Functions

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; 

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).

## Exploring NumPy's UFuncs

### Array arithmetic

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
The standard addition, subtraction, multiplication, and division can all be used:

In [93]:
# Lets create a and b
print(b)
print(a)


[ 0 10 20 30 40]
[0 1 2 3 4]


In [94]:
print("a     =", a)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * 2)
print("a / b =", a / b) # Nan
print("b / 0 =", b / 0)  # inf

a     = [0 1 2 3 4]
a + b = [ 0 11 22 33 44]
a - b = [  0  -9 -18 -27 -36]
a * b = [0 2 4 6 8]
a / b = [ nan  0.1  0.1  0.1  0.1]
b / 0 = [ nan  inf  inf  inf  inf]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


## Aggregations: Min, Max, and Everything In Between

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question.
Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here.

### Summing the Values in an Array

As a quick example, consider computing the sum of all values in an array.
Python itself can do this using the built-in ``sum`` function:


In [110]:
print(a)

[0 1 2 3 4]


In [95]:
a.sum() # Axis none

10

In [85]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [87]:
# Lets calculate the sum of arr matrix
np.sum(arr)

105

In [88]:
# Lets calculate the column- sum of arr matrix axis=0
np.sum(arr,axis = 0)

array([15, 18, 21, 24, 27])

In [89]:
# Lets calculate the row- sum of arr matrix axis=1
np.sum(arr, axis = 1)

array([10, 35, 60])

#### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [92]:
L = np.random.random(10)
# Lets calculate sum of these numbers use np.sum(L)
print(np.sum(L))
# min of these numbers
print(np.min(L))
# max
print(np.max(arr))
# sqrt
# square
print(np.sqrt(arr))
print(np.square(arr))

5.28603633213
0.175451756147
14
[[ 0.          1.          1.41421356  1.73205081  2.        ]
 [ 2.23606798  2.44948974  2.64575131  2.82842712  3.        ]
 [ 3.16227766  3.31662479  3.46410162  3.60555128  3.74165739]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


In [91]:
np.sum(L)

5.2451608825345613

In [94]:
arr1 = np.random.randint(100, size = 10)
print (arr1)

[94 27 34 97 76 40  3 69 64 75]


In [44]:
arr1.min()

25

In [45]:
np.min(arr1)

25

In [46]:
arr1.argmin() # index location

8

In [47]:
arr1.max()

97

In [48]:
arr1.argmax()

1

In [49]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [98]:
#Lets find the max number for each column
np.max(arr, axis = 0)

array([10, 11, 12, 13, 14])

In [114]:
#Lets find the max number for each row

array([ 4,  9, 14])

### Other aggregation functions

NumPy provides many other aggregation functions, but we won't discuss them in detail here.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |


### Trigonometric Functions
sin, cos, tan, atctan 

In [106]:
np.sin(arr1)

array([-0.96611777, -0.76825466,  0.6569866 , -0.99920683, -0.77946607,
        0.98662759,  0.37960774, -0.17607562, -0.24525199,  0.95637593])

In [107]:
np.cos(arr1)

array([-0.25810164, -0.64014434,  0.75390225,  0.03982088, -0.62644445,
       -0.16299078, -0.92514754, -0.98437664,  0.96945937, -0.29213881])

https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html


# Computation on Arrays: Broadcasting

We saw in the previous section how NumPy's universal functions can be used to *vectorize* operations and thereby remove slow Python loops.
Another means of vectorizing operations is to use NumPy's *broadcasting* functionality.
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

## Introducing Broadcasting

Recall that for arrays of the same size, binary operations are performed on an element-by-element basis:

In [216]:
x = np.arange(5)
print("x     =", x)
print("x + 10 =", x + 10)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)

x     = [0 1 2 3 4]
x + 10 = [10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]


## Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

To make these rules clear, let's consider a few examples in detail.

In [217]:
np.arange(3)+5

array([5, 6, 7])

In [54]:
# Lets create a and b and claculate c

array([[ 10.,  11.],
       [ 22.,  23.],
       [ 34.,  35.]])

In [219]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [116]:
np.arange(3).reshape((3,1))+np.arange(4).reshape((2,2))

ValueError: operands could not be broadcast together with shapes (3,1) (2,2) 

# Great Job!